# Fish completions for GitHub Copilot CLI

# Disable file completion by default
complete -c copilot -f

# Options
complete -c copilot -l add-dir -r -d 'Add a directory to the allowed list for file access'
complete -c copilot -l add-github-mcp-tool -r -d 'Add a tool to enable for the GitHub MCP server'
complete -c copilot -l add-github-mcp-toolset -r -d 'Add a toolset to enable for the GitHub MCP server'
complete -c copilot -l additional-mcp-config -r -d 'Additional MCP servers configuration as JSON string or file path'
complete -c copilot -l agent -x -a '(__fish_copilot_agents)' -d 'Specify a custom agent to use'
complete -c copilot -l allow-all -d 'Enable all permissions (equivalent to --allow-all-tools --allow-all-paths --allow-all-urls)'
complete -c copilot -l allow-all-paths -d 'Disable file path verification and allow access to any path'
complete -c copilot -l allow-all-tools -d 'Allow all tools to run automatically without confirmation'
complete -c copilot -l allow-all-urls -d 'Allow access to all URLs without confirmation'
complete -c copilot -l allow-tool -r -d 'Tools the CLI has permission to use'
complete -c copilot -l allow-url -r -d 'Allow access to specific URLs or domains'
complete -c copilot -l available-tools -r -d 'Only these tools will be available to the model'
complete -c copilot -l banner -d 'Show the startup banner'
complete -c copilot -l config-dir -r -d 'Set the configuration directory'
complete -c copilot -l continue -d 'Resume the most recent session'
complete -c copilot -l deny-tool -r -d 'Tools the CLI does not have permission to use'
complete -c copilot -l deny-url -r -d 'Deny access to specific URLs or domains'
complete -c copilot -l disable-builtin-mcps -d 'Disable all built-in MCP servers'
complete -c copilot -l disable-mcp-server -r -d 'Disable a specific MCP server'
complete -c copilot -l disable-parallel-tools-execution -d 'Disable parallel execution of tools'
complete -c copilot -l disallow-temp-dir -d 'Prevent automatic access to the system temporary directory'
complete -c copilot -l enable-all-github-mcp-tools -d 'Enable all GitHub MCP server tools'
complete -c copilot -l excluded-tools -r -d 'These tools will not be available to the model'
complete -c copilot -s h -l help -d 'Display help for command'
complete -c copilot -s i -l interactive -r -d 'Start interactive mode and automatically execute this prompt'
complete -c copilot -l log-dir -r -d 'Set log file directory'
complete -c copilot -l log-level -xa 'none error warning info debug all default' -d 'Set the log level'
complete -c copilot -l model -x -a '(__fish_copilot_models)' -d 'Set the AI model to use'
complete -c copilot -l no-ask-user -d 'Disable the ask_user tool (agent works autonomously)'
complete -c copilot -l no-auto-update -d 'Disable downloading CLI update automatically'
complete -c copilot -l no-color -d 'Disable all color output'
complete -c copilot -l no-custom-instructions -d 'Disable loading of custom instructions from AGENTS.md'
complete -c copilot -s p -l prompt -r -d 'Execute a prompt in non-interactive mode (exits after completion)'
complete -c copilot -l plain-diff -d 'Disable rich diff rendering'
complete -c copilot -l resume -d 'Resume from a previous session (optionally specify session ID)'
complete -c copilot -s s -l silent -d 'Output only the agent response, useful for scripting'
complete -c copilot -l screen-reader -d 'Enable screen reader optimizations'
complete -c copilot -l share -d 'Share session to markdown file after completion'
complete -c copilot -l share-gist -d 'Share session to a secret GitHub gist after completion'
complete -c copilot -l stream -xa 'on off' -d 'Enable or disable streaming mode'
complete -c copilot -s v -l version -d 'Show version information'
complete -c copilot -l yolo -d 'Enable all permissions (equivalent to --allow-all-tools --allow-all-paths --allow-all-urls)'

# Commands
complete -c copilot -n __fish_use_subcommand -a help -d 'Display help information'

# Help topics
complete -c copilot -n '__fish_seen_subcommand_from help' -a 'config' -d 'Configuration Settings'
complete -c copilot -n '__fish_seen_subcommand_from help' -a 'commands' -d 'Interactive Mode Commands'
complete -c copilot -n '__fish_seen_subcommand_from help' -a 'environment' -d 'Environment Variables'
complete -c copilot -n '__fish_seen_subcommand_from help' -a 'logging' -d 'Logging'
complete -c copilot -n '__fish_seen_subcommand_from help' -a 'permissions' -d 'Tool Permissions'
